apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: basillica/flask-api:v1
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: database_url
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: password
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app
# spec:
#   selector:
#     app: flask-app
#   ports:
#     - name: http
#       port: 80
#       targetPort: 3000
#   type: LoadBalancer


---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
  type: NodePort
